#!/usr/bin/env python3
"""The assessment's set arithmetic and referential integrity. Judgement stays with the model.

Six subcommands, and the division between them and the assessor is deliberate:

    resolve     graph + access  →  which of the 41 questions and 15 nodes are reachable
    record      append one observation to receipts.jsonl, validated, timestamped
    status      the frontier — what resolve says is reachable, minus what has a receipt
    findings    receipts → findings.yml, applying the supersedes chain
    validate    referential integrity across the six artifacts. NEVER fails on coverage
    selfcheck   the instrument itself: do the graph, the schema and the prose still agree?

A step belongs here when the reason is that a model under context pressure will skip it — not
when the script seems smarter. `resolve` earns its place because 41 access preconditions do not
fit in working memory. `findings` earns it because supersession chains are fiddly and fail
silently. There is deliberately **no `suggest`**: grouping findings into proposals requires
knowing that one NetworkPolicy closes three questions, which is knowledge of the system and not
set arithmetic. A script attempting it would bundle by pillar or by severity, which is the
"packaging" failure grouping rules exist to prevent. The model authors suggestions.yml;
`validate` checks it.

Artifacts, one writer each, under `.agentcore-migration/`:

    access.yml       survey 1 — what we were permitted to do        written once, by hand
    receipts.jsonl   append-only log of work actually done          appended by `record`
    findings.yml     everything observed, projected from receipts   generated by `findings`
    assessment.yml   the assessor's judgement                       model-authored
    suggestions.yml  grouped proposals, each citing findings        model-authored
    decisions.yml    survey 2 — proceed / decline / defer           written with the human
    plan/            plan.md + items.yml + scaffold/                written by /plan
"""
from __future__ import annotations

import argparse
import datetime as _dt
import json
import pathlib
import re
import sys

try:
    import yaml
except ImportError:
    sys.exit("needs pyyaml:  pip install pyyaml")

REFS = pathlib.Path(__file__).parent.parent / "skills/migrate-eks-to-agentcore/references"
GRAPH_PATH = REFS / "lens-graph.yaml"
SCHEMA_PATH = REFS / "record-schema.yaml"
DEFAULT_DIR = pathlib.Path(".agentcore-migration")

# Survey answer -> which access classes it grants.
GRANTS = {
    "source_available":          ["source"],
    "control_plane_read":        ["cluster", "logs"],
    "deployment_exists":         ["deployment"],
    "carries_real_traffic":      ["telemetry"],
    "invocation_permitted":      ["behaviour"],
    "load_generation_permitted": ["load"],
    "product_owner_reachable":   ["human"],
}

SURVEY_PROMPTS = [
    ("source_available", "S1  Is application source available to read?"),
    ("source_matches_deployment", "S1b Does that source match the deployed revision?"),
    ("control_plane_read", "S2  Do you have control-plane / cluster read access?"),
    ("account_is_customers", "S2b Are you in the customer's own AWS account?"),
    ("deployment_exists", "S3  Is there a running deployment?"),
    ("carries_real_traffic", "S3b Does it carry real user traffic?"),
    ("invocation_permitted", "S4  May you send requests to the agent?"),
    ("load_generation_permitted", "S5  May you generate concurrent load?"),
    ("product_owner_reachable", "S6  Is there someone who can answer product questions?"),
]

NODE_KINDS = ("question", "remedy", "node", "gate", "measurement", "topology", "artifact", "context",
              # written by /plan rather than /assess, into the same log. One log, because staleness
              # is only computable when the plan's verification and the observations it rests on
              # carry comparable timestamps.
              "plan_item")


# ── loading ─────────────────────────────────────────────────────────────────────────────────

def load_graph() -> dict:
    return yaml.safe_load(GRAPH_PATH.read_text())


def load_schema() -> dict:
    return yaml.safe_load(SCHEMA_PATH.read_text())


def load_yaml(path: pathlib.Path):
    if not path.exists():
        return None
    return yaml.safe_load(path.read_text()) or {}


def load_access(path: pathlib.Path) -> dict:
    raw = load_yaml(path)
    if raw is None:
        return {}
    return raw.get("access", raw) if isinstance(raw, dict) else {}


def load_receipts(d: pathlib.Path) -> list[dict]:
    f = d / "receipts.jsonl"
    if not f.exists():
        return []
    out = []
    for n, line in enumerate(f.read_text().splitlines(), 1):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            out.append(json.loads(line))
        except json.JSONDecodeError as e:
            sys.exit(f"receipts.jsonl:{n}: not valid JSON — {e}")
    return out


def now() -> str:
    return _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# ── resolve ─────────────────────────────────────────────────────────────────────────────────

def granted(access: dict) -> set[str]:
    have: set[str] = set()
    for key, classes in GRANTS.items():
        if access.get(key) is True:
            have.update(classes)
    # `aws` needs cluster-era credentials AND the customer's own account: reads in the wrong
    # account describe your infrastructure, which is worse than no answer.
    if access.get("control_plane_read") and access.get("account_is_customers"):
        have.add("aws")
    # Source is only evidence if it matches what is deployed.
    if access.get("source_available") and access.get("source_matches_deployment") is False:
        have.discard("source")
    return have


def _resolve_specs(specs: dict, have: set[str], multi_agent: bool | None) -> dict[str, str]:
    """Fixed-point over `after` edges, shared by questions and nodes."""
    state: dict[str, str] = {}
    for _ in range(len(specs) + 1):
        changed = False
        for qid, spec in specs.items():
            if qid in state:
                continue
            if spec.get("only_if") == "multi_agent" and multi_agent is False:
                state[qid] = "not_applicable"; changed = True; continue
            missing = [c for c in spec.get("needs", []) if c not in have]
            any_of = spec.get("needs_any") or []
            if any_of and not any(c in have for c in any_of):
                missing = missing + [" or ".join(any_of)]
            deps = spec.get("after", [])
            if [d for d in deps if d not in state]:
                continue
            unmet = [d for d in deps if state.get(d) != "reachable"]
            if missing:
                state[qid] = "blocked"
            elif unmet:
                state[qid] = "degraded"
            else:
                state[qid] = "reachable"
            changed = True
        if not changed:
            break
    return state


def _sort_key(s: str) -> tuple:
    digits = "".join(filter(str.isdigit, s))
    return (s[:8], int(digits) if digits else 0, s)


def _rows(specs: dict, state: dict, have: set[str]) -> list[dict]:
    out = []
    for qid in sorted(specs, key=_sort_key):
        spec = specs[qid]
        missing = [c for c in spec.get("needs", []) if c not in have]
        any_of = spec.get("needs_any") or []
        if any_of and not any(c in have for c in any_of):
            missing = missing + [" or ".join(any_of)]
        unmet = [d for d in spec.get("after", []) if state.get(d) in ("blocked", "not_applicable")]
        out.append({
            "id": qid,
            "state": state.get(qid, "reachable"),
            "missing_access": missing,
            "blocked_by": unmet,
            "substitute": spec.get("substitute"),
            "record_as": ("not_applicable" if state.get(qid) == "not_applicable"
                          else "unknown" if missing and not spec.get("substitute")
                          else None),
        })
    return out


def resolve(graph: dict, access: dict, multi_agent: bool | None) -> dict:
    have = granted(access)
    qstate = _resolve_specs(graph["questions"], have, multi_agent)
    nstate = _resolve_specs(graph.get("nodes", {}), have, multi_agent)
    return {
        "access_granted": sorted(have),
        "nodes": _rows(graph.get("nodes", {}), nstate, have),
        "questions": _rows(graph["questions"], qstate, have),
    }


def print_resolve(res: dict) -> None:
    have = res["access_granted"]
    print(f"access granted: {', '.join(have) or 'NOTHING — the assessment is not possible'}\n")
    for label, rows in (("check-graph nodes", res["nodes"]), ("Lens questions", res["questions"])):
        buckets = {"reachable": [], "degraded": [], "blocked": [], "not_applicable": []}
        for r in rows:
            buckets[r["state"]].append(r)
        print(f"── {label} ({len(rows)}) ──")
        print(f"  {'reachable':<16}{len(buckets['reachable']):>3}  answer these normally")
        print(f"  {'degraded':<16}{len(buckets['degraded']):>3}  a prerequisite is unanswerable")
        print(f"  {'blocked':<16}{len(buckets['blocked']):>3}  access missing")
        print(f"  {'not_applicable':<16}{len(buckets['not_applicable']):>3}  shape does not apply")
        for name in ("blocked", "degraded", "not_applicable"):
            if not buckets[name]:
                continue
            print(f"\n  ── {name} ──")
            for r in buckets[name]:
                why = ", ".join(r["missing_access"] or r["blocked_by"]) or "shape"
                print(f"    {r['id']:<13} needs: {why}")
                if r["substitute"]:
                    print(f"                  → {r['substitute']}")
                elif name == "blocked":
                    print("                  → nothing substitutes. Record `unknown` with the "
                          "blocker, NOT `absent`.")
        print()
    print("Everything above that is not `reachable` belongs in a receipt with its blocker.")
    print("None of it is a finding about the customer.")


# ── record ──────────────────────────────────────────────────────────────────────────────────

KIND_FLAGS = {
    "question": "--question", "remedy": "--remedy", "node": "--node", "gate": "--gate",
    "measurement": "--measurement", "topology": "--topology", "artifact": "--artifact",
    "context": "--context", "plan_item": "--plan-item",
}


def valid_subjects(kind: str, graph: dict, schema: dict) -> set[str] | None:
    """None means free text."""
    return {
        "question": set(graph["questions"]),
        "remedy": set(graph["questions"]),
        "node": set(graph.get("nodes", {})),
        "gate": set(schema["gate_ids"]),
        "measurement": set(schema["measurement_fields"]),
        "topology": set(schema["topology_fields"]),
        "context": set(schema["context_fields"]),
        "artifact": None,
        # Free text here, cross-checked against plan/items.yml by `validate` instead. The id is
        # authored by /plan, so there is no fixed vocabulary to validate against at record time —
        # and requiring items.yml to exist first would make the receipt unwritable during the run
        # that produces it.
        "plan_item": None,
    }[kind]


def coerce(text: str):
    """`record` takes strings; findings.yml should carry numbers and booleans as themselves."""
    low = text.strip().lower()
    if low in ("true", "yes"):
        return True
    if low in ("false", "no"):
        return False
    if low in ("none", "null"):
        return None
    try:
        return int(text)
    except ValueError:
        pass
    try:
        return float(text)
    except ValueError:
        return text


def validate_receipt(rec: dict, graph: dict, schema: dict, known_ids: set[str]) -> list[str]:
    errs = []
    kind = rec.get("kind")
    spec = schema["kinds"].get(kind)
    if spec is None:
        return [f"kind `{kind}` is not one of {', '.join(NODE_KINDS)}"]

    subject = rec.get("subject")
    allowed = valid_subjects(kind, graph, schema)
    if not subject:
        errs.append(f"kind {kind} needs a subject")
    elif allowed is not None and subject not in allowed:
        stem = (re.match(r"[A-Za-z_]+", str(subject)) or re.match("", "")).group(0).lower()
        near: list[str] = []
        while stem and not near:
            near = [s for s in sorted(allowed) if s.lower().startswith(stem)]
            stem = stem[:-1]
        errs.append(f"`{subject}` is not a known {kind} subject"
                    + (f" — did you mean {', '.join(near[:4])}?" if near else ""))

    tag = rec.get("tag")
    if tag not in schema["evidence_tags"]:
        errs.append(f"tag `{tag}` is not in evidence.md's tag set")
    if not rec.get("evidence"):
        errs.append("every receipt needs `evidence` — what you saw, at file:line where there is one")
    if tag in schema["tags_requiring_source"] and not rec.get("source"):
        errs.append(f"tag `{tag}` asserts an observation, so `source` is required: "
                    "the command you ran or the artifact you opened")

    states = spec.get("state")
    if states:
        if rec.get("state") not in states:
            errs.append(f"kind {kind} needs --state one of: {', '.join(states)}")
    elif "state" in rec:
        errs.append(f"kind {kind} takes no --state")

    if spec.get("takes_value") and "value" not in rec:
        errs.append(f"kind {kind} needs --value")

    if kind == "remedy" and rec.get("closed_by") not in schema["enums"]["closed_by"]:
        errs.append("kind remedy needs --closed-by one of: " + ", ".join(schema["enums"]["closed_by"]))

    for field, enum in (("ineffective_because", "ineffective_because"),
                        ("defect_owner", "defect_owner"),
                        ("compute_type_assumed", "compute_type_assumed"),
                        ("source_of_value", "source_of_value"),
                        ("by", "by")):
        if field in rec and rec[field] not in schema["enums"][enum]:
            errs.append(f"{field}=`{rec[field]}` not in: {', '.join(map(str, schema['enums'][enum]))}")

    if kind == "topology" and subject in schema["topology_fields"]:
        legal = schema["topology_fields"][subject]
        if isinstance(legal, list) and rec.get("value") not in legal:
            errs.append(f"topology {subject} must be one of: {', '.join(map(str, legal))}")

    if rec.get("state") == "present_but_ineffective" and "ineffective_because" not in rec:
        errs.append("`present_but_ineffective` needs --ineffective-because. "
                    "`effective: false` alone restated the state on 13 of 14 rows measured")

    if kind == "plan_item":
        state = rec.get("state")
        if state in ("built", "failing") and not rec.get("verified_by"):
            errs.append(f"`{state}` needs --verified-by: the command you actually ran. Without it "
                        "the receipt asserts execution and records nothing about it, which is the "
                        "defect this kind exists to close")
        if state == "unverifiable" and not rec.get("blocked_by"):
            errs.append("`unverifiable` needs --blocked-by. An artifact nobody could run is a fine "
                        "outcome; one with no stated reason is indistinguishable from untried")
        if state in ("unverifiable", "planned") and rec.get("verified_by"):
            errs.append(f"`{state}` takes no --verified-by — it says nothing was run. Use `built` "
                        "or `failing` if something was")

    if "supersedes" in rec:
        if rec["supersedes"] not in known_ids:
            errs.append(f"supersedes `{rec['supersedes']}`, which is not an existing receipt id")
        if rec.get("reason") not in schema["enums"]["supersede_reason"]:
            errs.append("a superseding receipt needs --reason reinterpretation|re-observation. "
                        "Keep them distinct: reinterpretation means nobody looked again")

    known_fields = {"id", "at", "by", "kind", "subject", "state", "value", "tag", "evidence",
                    "source", "note", "supersedes", "reason"} | set(spec.get("optional", [])) \
                   | set(spec.get("requires", []))
    for k in rec:
        if k not in known_fields:
            errs.append(f"kind {kind} has no field `{k}` (record-schema.yaml lists what it takes)")
    return errs


def next_id(receipts: list[dict]) -> str:
    n = 0
    for r in receipts:
        m = re.fullmatch(r"r-(\d+)", str(r.get("id", "")))
        if m:
            n = max(n, int(m.group(1)))
    return f"r-{n + 1:04d}"


def cmd_record(a, graph: dict, schema: dict) -> int:
    d = a.dir
    receipts = load_receipts(d)
    known = {r.get("id") for r in receipts}
    pending: list[dict] = []

    if a.batch:
        src = sys.stdin.read() if a.batch == "-" else pathlib.Path(a.batch).read_text()
        for n, line in enumerate(src.splitlines(), 1):
            if line.strip():
                try:
                    pending.append(json.loads(line))
                except json.JSONDecodeError as e:
                    return err(f"--batch line {n}: {e}")
    else:
        chosen = [(k, getattr(a, k)) for k in NODE_KINDS if getattr(a, k, None)]
        if len(chosen) != 1:
            return err("give exactly one of " + ", ".join(KIND_FLAGS.values()) + ", or --batch")
        kind, subject = chosen[0]
        rec = {"kind": kind, "subject": subject}
        for flag, field in (("state", "state"), ("tag", "tag"), ("evidence", "evidence"),
                            ("source", "source"), ("note", "note"), ("component", "component"),
                            ("blocked_by", "blocked_by"), ("substitute_used", "substitute_used"),
                            ("closed_by", "closed_by"), ("remedy_verified", "remedy_verified"),
                            ("requires_runtime_move", "requires_runtime_move"),
                            ("ineffective_because", "ineffective_because"),
                            ("defect_owner", "defect_owner"),
                            ("blocked_by_artifact", "blocked_by_artifact"),
                            ("compute_type_assumed", "compute_type_assumed"),
                            ("source_of_value", "source_of_value"),
                            ("is_true_high_water_mark", "is_true_high_water_mark"),
                            ("derived_from", "derived_from"), ("how_to_get_it", "how_to_get_it"),
                            ("verified_by", "verified_by"), ("mutation_tested", "mutation_tested"),
                            ("artifacts", "artifacts"),
                            ("supersedes", "supersedes"), ("reason", "reason")):
            v = getattr(a, flag, None)
            if v is not None:
                rec[field] = coerce(v) if field in (
                    "remedy_verified", "requires_runtime_move", "is_true_high_water_mark",
                    "mutation_tested") else v
        # A comma-separated list is what a shell can produce; a list is what MANIFEST.md needs.
        if isinstance(rec.get("artifacts"), str):
            rec["artifacts"] = [p.strip() for p in rec["artifacts"].split(",") if p.strip()]
        if a.value is not None:
            rec["value"] = coerce(a.value)
        if a.by:
            rec["by"] = a.by
        pending.append(rec)

    stamped, problems = [], []
    for rec in pending:
        rec.pop("id", None)
        rec.pop("at", None)
        rid = next_id(receipts + stamped)
        # id and `at` are the script's, never the model's. That is what makes staleness
        # computable, and what makes a batch written at write-up time visible as a cluster of
        # identical timestamps a long way from the tool calls that should have produced it.
        full = {"id": rid, "at": now(), **rec}
        errs = validate_receipt(full, graph, schema, known | {r["id"] for r in stamped})
        if errs:
            problems.append((rec.get("kind"), rec.get("subject"), errs))
        else:
            stamped.append(full)

    if problems:
        for kind, subject, errs in problems:
            print(f"rejected {kind} {subject}:", file=sys.stderr)
            for e in errs:
                print(f"  - {e}", file=sys.stderr)
        print("\nNothing was written. An invalid receipt is worse than none — it looks like "
              "evidence.", file=sys.stderr)
        return 1

    d.mkdir(parents=True, exist_ok=True)
    with (d / "receipts.jsonl").open("a") as fh:
        for full in stamped:
            fh.write(json.dumps(full, ensure_ascii=False) + "\n")
    for full in stamped:
        print(f"{full['id']}  {full['kind']} {full['subject']}"
              + (f" → {full['state']}" if "state" in full else "")
              + (f" = {full['value']}" if "value" in full else "")
              + (f"  (supersedes {full['supersedes']})" if "supersedes" in full else ""))
    return 0


# ── findings ────────────────────────────────────────────────────────────────────────────────

def split_supersession(receipts: list[dict]) -> tuple[list[dict], dict[str, dict]]:
    """Returns (effective, superseded_by). A chain works because each link names one predecessor."""
    superseded_by = {}
    for r in receipts:
        if r.get("supersedes"):
            superseded_by[r["supersedes"]] = r
    effective = [r for r in receipts if r.get("id") not in superseded_by]
    return effective, superseded_by


def finding_key(r: dict) -> str:
    return f"{r['subject']}/{r['component']}" if r.get("component") else r["subject"]


def build_findings(receipts: list[dict], graph: dict) -> dict:
    effective, superseded_by = split_supersession(receipts)
    by_id = {r["id"]: r for r in receipts}

    def latest(kind: str, keyfn) -> dict:
        out: dict = {}
        for r in effective:
            if r.get("kind") == kind:
                out[keyfn(r)] = r
        return out

    q_latest = latest("question", finding_key)
    remedies: dict[str, list[dict]] = {}
    for r in effective:
        if r.get("kind") == "remedy":
            remedies.setdefault(finding_key(r), []).append(r)

    def history(key: str, kinds: tuple[str, ...]) -> list[dict]:
        out = []
        for r in receipts:
            if r.get("kind") in kinds and finding_key(r) == key and r["id"] in superseded_by:
                nxt = superseded_by[r["id"]]
                out.append({"receipt": r["id"], "superseded_by": nxt["id"],
                            "reason": nxt.get("reason"),
                            "was": r.get("state", r.get("value")),
                            "note": nxt.get("note")})
        return out

    findings = []
    for key in sorted(set(q_latest) | set(remedies), key=_sort_key):
        q = q_latest.get(key)
        rs = remedies.get(key, [])
        row = {"id": key,
               "practice": (q or rs[0])["subject"],
               "component": (q or rs[0]).get("component")}
        if q:
            row.update({k: q[k] for k in ("state", "ineffective_because", "defect_owner",
                                          "evidence", "tag", "note", "blocked_by_artifact")
                        if k in q})
        else:
            # A remedy with no state receipt: a claim about a fix for something never observed.
            row["state"] = "unknown"
            row["note"] = "remedy recorded with no observation of the question itself"
        if rs:
            row["closed_by"] = sorted({r["closed_by"] for r in rs})
            verified = [r.get("remedy_verified") for r in rs]
            row["remedy_verified"] = (True if all(v is True for v in verified)
                                      else "unverifiable" if "unverifiable" in verified else False)
            rrm = [r.get("requires_runtime_move") for r in rs if "requires_runtime_move" in r]
            if rrm:
                row["requires_runtime_move"] = any(rrm)
        row["receipts"] = [r["id"] for r in ([q] if q else []) + rs]
        hist = history(key, ("question", "remedy"))
        if hist:
            row["history"] = hist
        findings.append({k: v for k, v in row.items() if v is not None})

    artifacts = []
    for key, r in latest("artifact", lambda x: x["subject"]).items():
        blocks = sorted({e["subject"] for e in effective
                         if e.get("blocked_by_artifact") == key}, key=_sort_key)
        artifacts.append({"artifact": key, "blocks": blocks, "receipt": r["id"],
                          "how_to_get_it": r.get("how_to_get_it"), "evidence": r.get("evidence")})

    def val_block(kind: str, keyfn=lambda r: r["subject"]) -> dict:
        out = {}
        for key, r in latest(kind, keyfn).items():
            entry = {"value": r.get("value"), "tag": r.get("tag"), "evidence": r.get("evidence"),
                     "receipts": [r["id"]] + [h["receipt"] for h in history(key, (kind,))]}
            for extra in ("source_of_value", "is_true_high_water_mark", "derived_from", "component"):
                if extra in r:
                    entry[extra] = r[extra]
            hist = history(key, (kind,))
            if hist:
                entry["history"] = hist
            out[key] = {k: v for k, v in entry.items() if v is not None}
        return out

    assessed = sorted({r["subject"] for r in effective if r.get("kind") == "question"}, key=_sort_key)
    all_q = set(graph["questions"])

    walk = []
    for nid, r in sorted(latest("node", lambda x: x["subject"]).items(), key=lambda kv: _sort_key(kv[0])):
        walk.append({k: v for k, v in {
            "node": nid, "state": r.get("state"), "blocked_by": r.get("blocked_by"),
            "substitute_used": r.get("substitute_used"), "evidence": r.get("evidence"),
            "receipt": r["id"]}.items() if v is not None})

    return {
        "generated_at": now(),
        "generated_by": "lens_plan.py findings — DO NOT HAND-EDIT. A correction is a new receipt.",
        "generated_from": {"receipts": len(receipts), "superseded": len(superseded_by),
                           "newest_receipt_at": max((r.get("at", "") for r in receipts), default=None)},
        "context": {k: v.get("value") for k, v in val_block("context").items()},
        "walk": walk,
        "gates": [{"check": k, "result": r.get("state"), "tag": r.get("tag"),
                   "evidence": r.get("evidence"),
                   "compute_type_assumed": r.get("compute_type_assumed"),
                   "receipt": r["id"]}
                  for k, r in sorted(latest("gate", lambda x: x["subject"]).items())],
        "topology": val_block("topology", finding_key),
        "measurements": val_block("measurement"),
        "network": {},
        "missing_artifacts": artifacts,
        "lens_coverage": {
            "scope": "questions_only",
            "questions_assessed": len(assessed),
            "questions_total": len(all_q),
            "inventory_rows": len(findings),
            "best_practices_assessed": 0,
            "no_receipt": sorted(all_q - set(assessed), key=_sort_key),
        },
        "findings": findings,
    }


def cmd_findings(a, graph: dict, schema: dict) -> int:
    receipts = load_receipts(a.dir)
    if not receipts:
        return err("no receipts.jsonl — nothing to derive findings from")
    doc = build_findings(receipts, graph)
    # network is a view over measurements, not a separate observation class.
    net = {k: v for k, v in doc["measurements"].items()
           if k.startswith(("vpc_", "existing_"))}
    doc["network"] = net
    for k in net:
        doc["measurements"].pop(k)
    out = a.dir / "findings.yml"
    a.dir.mkdir(parents=True, exist_ok=True)
    out.write_text(yaml.dump(doc, sort_keys=False, allow_unicode=True, width=100))
    c = doc["lens_coverage"]
    print(f"{out}: {c['inventory_rows']} rows over {c['questions_assessed']} of "
          f"{c['questions_total']} questions, from {doc['generated_from']['receipts']} receipts "
          f"({doc['generated_from']['superseded']} superseded)")
    if c["no_receipt"]:
        print(f"  no receipt yet: {len(c['no_receipt'])} questions — "
              "that is the frontier, not a finding about the customer")
    return 0


# ── status ──────────────────────────────────────────────────────────────────────────────────

def cmd_status(a, graph: dict, schema: dict) -> int:
    d = a.dir
    receipts = load_receipts(d)
    effective, _ = split_supersession(receipts)
    access = load_access(a.access or (d / "access.yml"))
    res = resolve(graph, access, {"yes": True, "no": False, "unknown": None}[a.multi_agent])

    def seen(kind: str) -> dict[str, str]:
        return {r["subject"]: r.get("state", "recorded") for r in effective if r.get("kind") == kind}

    q_seen, n_seen = seen("question"), seen("node")
    lines = []
    for label, rows, got in (("nodes", res["nodes"], n_seen), ("questions", res["questions"], q_seen)):
        reach = [r["id"] for r in rows if r["state"] in ("reachable", "degraded")]
        frontier = [i for i in reach if i not in got]
        lines.append(f"{label}: {len(got)}/{len(rows)} receipted, {len(frontier)} reachable and open")
        if frontier:
            lines.append(f"  next: {' '.join(frontier[:12])}" + (" …" if len(frontier) > 12 else ""))

    unreachable = [r for r in res["nodes"] + res["questions"] if r["state"] == "blocked"]
    unrecorded = [r["id"] for r in unreachable if r["id"] not in q_seen and r["id"] not in n_seen]

    # Divergence, reported and not judged: a state recorded on something access could not reach.
    # This is the failure the whole instrument exists to prevent, and it is now computable.
    blocked = {r["id"] for r in res["nodes"] + res["questions"] if r["state"] == "blocked"}
    overclaimed = [(i, s) for i, s in {**q_seen, **n_seen}.items()
                   if i in blocked and s not in ("unknown", "not_applicable", "unreachable")]

    print(f"access: {', '.join(res['access_granted']) or 'NOTHING'}")
    for l in lines:
        print(l)
    if unrecorded:
        print(f"unreachable and not yet recorded as such: {' '.join(sorted(unrecorded, key=_sort_key)[:12])}")
    if overclaimed:
        print("\n── divergence (reported, not judged) ──")
        for i, s in overclaimed:
            print(f"  {i} recorded `{s}` but access for it is missing. If that came from a "
                  "substitute, say which in the receipt; if not, it is a claim about your access.")
    fy = d / "findings.yml"
    if receipts and fy.exists():
        gen = (load_yaml(fy) or {}).get("generated_at", "")
        newest = max((r.get("at", "") for r in receipts), default="")
        if newest > gen:
            print("\nfindings.yml is older than the newest receipt — run `lens_plan.py findings`")
    return 0


# ── validate ────────────────────────────────────────────────────────────────────────────────

def cmd_validate(a, graph: dict, schema: dict) -> int:
    d = a.dir
    errors: list[str] = []
    notes: list[str] = []

    receipts = load_receipts(d)
    effective, superseded_by = split_supersession(receipts)
    ids = {r.get("id") for r in receipts}
    findings_doc = load_yaml(d / "findings.yml") or {}
    findings = {f["id"]: f for f in findings_doc.get("findings", [])}
    suggestions_doc = load_yaml(d / "suggestions.yml") or {}
    suggestions = {s["id"]: s for s in suggestions_doc.get("suggestions", [])}
    decisions_doc = load_yaml(d / "decisions.yml") or {}
    decisions = {x["id"]: x for x in decisions_doc.get("decisions", [])}
    # /plan writes to .agentcore-migration/plan/ by default, but --out can put it elsewhere; accept
    # a top-level items.yml too rather than silently checking nothing.
    plan_doc = (load_yaml(d / "plan" / "items.yml") or load_yaml(d / "items.yml") or {})
    assessment = load_yaml(d / "assessment.yml") or {}

    # ── referential errors. These, and only these, fail. ──
    for r in receipts:
        errs = validate_receipt(r, graph, schema, ids - {r.get("id")})
        for e in errs:
            errors.append(f"receipts.jsonl {r.get('id')}: {e}")

    for f in findings.values():
        if not f.get("receipts"):
            errors.append(f"findings.yml {f['id']}: no receipt. findings.yml is generated — "
                          "if this was hand-edited, the audit trail is broken. Re-run `findings`")

    for s in suggestions.values():
        for field in schema["suggestion_required_fields"]:
            if field not in s or s[field] in (None, [], ""):
                if field in ("closes", "grounded_in"):
                    errors.append(f"suggestions.yml {s.get('id')}: `{field}` is empty. "
                                  "Grounding is structural, not optional")
                else:
                    notes.append(f"suggestions.yml {s.get('id')}: missing `{field}` — incomplete. "
                                 "A suggestion without it is a pitch with citations")
        for fid in s.get("closes") or []:
            if fid not in findings:
                near = [k for k in findings if k.split("/")[0] == str(fid).split("/")[0]]
                errors.append(f"suggestions.yml {s.get('id')}: closes `{fid}`, which is not a finding id"
                              + (f" — did you mean {', '.join(near)}?" if near else ""))
        for rid in s.get("grounded_in") or []:
            if rid not in ids:
                errors.append(f"suggestions.yml {s.get('id')}: grounded_in `{rid}`, not a receipt id")
        if s.get("confidence") and s["confidence"] not in schema["suggestion_confidence"]:
            errors.append(f"suggestions.yml {s.get('id')}: confidence `{s['confidence']}` is not "
                          + "/".join(schema["suggestion_confidence"]))

    for x in decisions.values():
        choice = x.get("choice")
        rules = schema["decision_choices"]
        if choice not in rules:
            errors.append(f"decisions.yml {x.get('id')}: choice `{choice}` is not one of "
                          + ", ".join(rules) + ". There is deliberately no `undecided` — "
                          "an undecided suggestion has no entry")
            continue
        for field in (rules[choice] or {}).get("requires", []):
            if not x.get(field):
                errors.append(f"decisions.yml {x['id']}: choice `{choice}` requires `{field}`. "
                              "Captured now, not reconstructed later — this is the direction a "
                              "human revisiting actually asks about")
        if x.get("suggestion") not in suggestions:
            errors.append(f"decisions.yml {x.get('id')}: suggestion `{x.get('suggestion')}` does not exist")
        for fid in x.get("residual_gaps") or []:
            if fid not in findings:
                errors.append(f"decisions.yml {x['id']}: residual_gaps `{fid}` is not a finding id")

    if decisions_doc:
        out = decisions_doc.get("outcome")
        if out and out not in schema["outcomes"]:
            errors.append(f"decisions.yml: outcome `{out}` is not one of " + ", ".join(schema["outcomes"]))
        if not decisions_doc.get("decided_with"):
            notes.append("decisions.yml has no `decided_with` — nobody is recorded as having chosen, "
                         "so every entry is the assessor's own verdict wearing a decision's clothes")

    item_ids = set()
    for item in plan_doc.get("items", []):
        item_ids.add(item.get("id"))
        did = item.get("decision")
        if not did:
            errors.append(f"plan/items.yml {item.get('id')}: no decision id. A plan item with no "
                          "decision quietly reintroduces something the customer declined")
        elif did not in decisions:
            errors.append(f"plan/items.yml {item.get('id')}: decision `{did}` does not exist")
        elif decisions[did].get("choice") != "proceed":
            errors.append(f"plan/items.yml {item.get('id')}: decision {did} is "
                          f"`{decisions[did].get('choice')}`, not `proceed`")
        # Verification is not storable here. items.yml is written by the same pass that would claim
        # the verification, so a status field in it is a self-assertion with nothing to check it —
        # the defect that deleting the old `plan:` block removed from the assessment side.
        for banned in ("verified", "built", "status", "state", "tested", "passing"):
            if banned in item:
                errors.append(f"plan/items.yml {item.get('id')}: has `{banned}`. Verification lives "
                              "in a plan_item receipt, not here — this field can only ever restate "
                              "what the writer hoped. Use `record --plan-item`")

    for r in effective:
        if r.get("kind") != "plan_item":
            continue
        if plan_doc and r["subject"] not in item_ids:
            near = [i for i in sorted(item_ids) if str(i)[:3] == str(r["subject"])[:3]]
            errors.append(f"receipts.jsonl {r['id']}: plan_item `{r['subject']}` is in no "
                          "plan/items.yml entry"
                          + (f" — did you mean {', '.join(map(str, near[:3]))}?" if near else ""))

    # ── reports. Never fail on these. `unreachable` and `not_permitted` are recordable states,
    # and a hook that punishes an incomplete walk teaches assessors to fabricate receipts. ──
    needs_action = {k: f for k, f in findings.items()
                    if f.get("state") in ("absent", "present_but_ineffective",
                                          "available_unconfigured")}
    covered = {fid for s in suggestions.values() for fid in (s.get("closes") or [])}
    for k in needs_action:
        if k not in covered:
            notes.append(f"uncovered: {k} is `{needs_action[k]['state']}` and appears in no "
                         "suggestion. Deliberate is fine — say so in assessment.yml's triage")
    seen_twice = {}
    for s in suggestions.values():
        for fid in s.get("closes") or []:
            seen_twice.setdefault(fid, []).append(s.get("id"))
    for fid, sids in seen_twice.items():
        if len(sids) > 1:
            notes.append(f"{fid} is closed by {' and '.join(sids)}. Not necessarily wrong — but if "
                         "one change closes it, they are one suggestion (grouping rule 2)")
    for sid in suggestions:
        if not any(x.get("suggestion") == sid for x in decisions.values()):
            notes.append(f"{sid} has no decision — undecided by absence, which is honest. "
                         "Survey 2 has not covered it")

    # Plan-side coverage. Notes, not errors: the same reasoning as the assessment walk — punishing
    # an incomplete record teaches people to write receipts for work they did not do, and an item
    # nobody could run is an honest outcome that `unverifiable` exists to carry.
    pi = {}
    for r in effective:
        if r.get("kind") == "plan_item":
            pi.setdefault(r["subject"], []).append(r)
    for iid in sorted(item_ids, key=lambda x: _sort_key(str(x))):
        if iid not in pi:
            notes.append(f"plan item {iid} has no plan_item receipt — nothing records whether it was "
                         "built, ran, or could not be run. plan.md must not describe it as verified")
    for iid, rs in sorted(pi.items(), key=lambda kv: _sort_key(str(kv[0]))):
        last = rs[-1]
        if last.get("state") == "built" and "mutation_tested" not in last:
            notes.append(f"plan item {iid} is `built` with no mutation_tested. Measured on one "
                         "generated suite, 3 of 6 assertions could not fail — and all 3 passed")
        elif last.get("state") == "built" and last.get("mutation_tested") is False:
            notes.append(f"plan item {iid} is `built` and mutation_tested: false. Passing is not "
                         "evidence until you have broken it once — say so in plan.md at that step")
        if last.get("state") == "failing":
            notes.append(f"plan item {iid} is `failing` ({last.get('verified_by')}). A plan whose "
                         "first concrete action fails is worse than no plan — fix or restate it")

    # MANIFEST.md was absent entirely on the one real plan produced, along with items.yml — the two
    # files whose only job is catching omission. Absence is not a referential error, so this is a
    # note; but it is the note most worth printing, because nothing else in the record misses it.
    if item_ids:
        man = next((p for p in (d / "plan" / "scaffold" / "MANIFEST.md",
                                d / "scaffold" / "MANIFEST.md") if p.exists()), None)
        if man is None:
            notes.append("plan items exist but no scaffold/MANIFEST.md — run `lens_plan.py "
                         "manifest`. Its reverse index is the only thing that catches a decision "
                         "with no plan item, which is how one plan skipped a severity: high finding "
                         "while claiming thirteen closed")
        elif pi:
            newest_pi = max(r.get("at", "") for rs in pi.values() for r in rs)
            written = _dt.datetime.fromtimestamp(man.stat().st_mtime, _dt.timezone.utc) \
                         .strftime("%Y-%m-%dT%H:%M:%SZ")
            if newest_pi > written:
                notes.append("scaffold/MANIFEST.md is older than the newest plan_item receipt — "
                             "re-run `lens_plan.py manifest` so its verified column matches the log")

    triaged = {t.get("finding") for t in (assessment.get("triage") or [])}
    for k, f in findings.items():
        if f.get("state") == "absent" and k not in triaged:
            notes.append(f"{k} is absent with no severity in assessment.yml's triage")

    if receipts and findings_doc:
        newest = max((r.get("at", "") for r in receipts), default="")
        if newest > findings_doc.get("generated_at", ""):
            msg = "findings.yml is older than the newest receipt — run `lens_plan.py findings`"
            (errors if decisions else notes).append(
                msg + (". Decisions rest on it, so this is not cosmetic" if decisions else ""))

    for x in decisions.values():
        s = suggestions.get(x.get("suggestion")) or {}
        stale = [r for r in (s.get("grounded_in") or []) if r in superseded_by]
        if stale:
            notes.append(f"{x.get('id')} rests on {', '.join(stale)}, since superseded "
                         f"({superseded_by[stale[0]].get('reason')}). Re-check before planning it")

    if effective and not any(r.get("kind") == "context" and r["subject"] == "code_ownership"
                             for r in effective):
        notes.append("no code_ownership receipt. It decides whether a remedy is actionable at all — "
                     "on a third-party platform `customer_code` is not available to recommend")

    for line in errors:
        print(f"ERROR  {line}")
    if errors and notes:
        print()
    for line in notes:
        print(f"note   {line}")
    if not errors and not notes:
        print("validate: clean")
    elif not errors:
        print(f"\nvalidate: {len(notes)} note(s), no referential errors. Coverage is never an error — "
              "`unreachable` and `not_permitted` are recordable states.")
    return 1 if errors else 0


# ── manifest ────────────────────────────────────────────────────────────────────────────────

VERIFIED_LABEL = {
    "built": "built, ran, passed",
    "failing": "**ran and FAILED**",
    "unverifiable": "generated, not runnable here",
    "planned": "not executed by design",
}


def cmd_manifest(a, graph: dict, schema: dict) -> int:
    """MANIFEST.md, generated. The forward index catches invention; the reverse index catches
    omission, which is the failure that actually happened — one plan skipped a severity: high
    finding entirely while claiming thirteen closed. Nothing in its artifact list was wrong; the
    list simply ended. Assembling this by hand is how that survives, so it is generated."""
    d = a.dir
    out = pathlib.Path(a.out) if a.out else d / "plan"
    plan_doc = load_yaml(out / "items.yml") or load_yaml(d / "plan" / "items.yml") \
        or load_yaml(d / "items.yml") or {}
    items = plan_doc.get("items", [])
    if not items:
        return err(f"no items.yml under {out} — /plan writes it before this runs. A manifest with "
                   "no items would report full coverage of nothing")

    decisions = {x["id"]: x for x in (load_yaml(d / "decisions.yml") or {}).get("decisions", [])}
    suggestions = {s["id"]: s for s in (load_yaml(d / "suggestions.yml") or {}).get("suggestions", [])}
    effective, _ = split_supersession(load_receipts(d))
    latest_pi: dict[str, dict] = {}
    for r in effective:
        if r.get("kind") == "plan_item":
            latest_pi[r["subject"]] = r

    by_decision: dict[str, list[dict]] = {}
    for it in items:
        by_decision.setdefault(it.get("decision"), []).append(it)

    L = [f"# Plan manifest — generated by `lens_plan.py manifest` at {now()}", "",
         "Do not hand-edit. The verified column is projected from `plan_item` receipts, so a row",
         "cannot claim verification that was never recorded.", ""]

    L += ["## Artifact → decision (catches invention)", "",
          "| Artifact | Item | Decision | Closes | Verified |", "|---|---|---|---|---|"]
    for it in items:
        rec = latest_pi.get(it.get("id")) or {}
        arts = rec.get("artifacts") or it.get("artifacts") or ["—"]
        sug = suggestions.get((decisions.get(it.get("decision")) or {}).get("suggestion")) or {}
        closes = ", ".join(sug.get("closes") or []) or "—"
        label = VERIFIED_LABEL.get(rec.get("state"), "**no receipt**")
        if rec.get("state") == "built" and rec.get("mutation_tested") is not True:
            label += " (not mutation-tested)"
        for n, art in enumerate(arts):
            L.append(f"| `{art}` | {it.get('id') if n == 0 else ''} "
                     f"| {it.get('decision') if n == 0 else ''} | {closes if n == 0 else ''} "
                     f"| {label if n == 0 else ''} |")

    L += ["", "## Decision → artifact (catches omission)", "",
          "Every `proceed` decision appears here. `not addressed` is a fine answer — writing it",
          "turns a gap in the plan into something the customer can overrule.", "",
          "| Decision | Choice | Plan items | Or why not |", "|---|---|---|---|"]
    n_proceed = n_addressed = 0
    for did, x in sorted(decisions.items()):
        if x.get("choice") != "proceed":
            continue
        n_proceed += 1
        got = by_decision.get(did) or []
        if got:
            n_addressed += 1
        L.append(f"| {did} | proceed | {', '.join(str(i.get('id')) for i in got) or '—'} "
                 f"| {'' if got else '**NOT ADDRESSED — state the reason here**'} |")

    other = [(k, v) for k, v in sorted(decisions.items()) if v.get("choice") != "proceed"]
    if other:
        L += ["", "## Declined and deferred (so the plan does not read as if nothing was refused)",
              "", "| Decision | Choice | In their words |", "|---|---|---|"]
        for did, x in other:
            why = x.get("reason") or x.get("revisit_when") or x.get("rationale") or "—"
            L.append(f"| {did} | {x.get('choice')} | {str(why).replace(chr(10), ' ')} |")

    counts: dict[str, int] = {}
    for it in items:
        counts[(latest_pi.get(it.get("id")) or {}).get("state") or "no receipt"] = \
            counts.get((latest_pi.get(it.get("id")) or {}).get("state") or "no receipt", 0) + 1
    L += ["", "## Counts, derived — not asserted", "",
          f"- plan items: **{len(items)}**",
          f"- `proceed` decisions: **{n_proceed}**, with at least one plan item: **{n_addressed}**",
          "- item states: " + ", ".join(f"{k} {v}" for k, v in sorted(counts.items())), "",
          "Any claim in `plan.md` about how many findings were closed must be derived from the",
          "second table above, not from the record's severity totals."]

    out.mkdir(parents=True, exist_ok=True)
    target = out / "scaffold" / "MANIFEST.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(L) + "\n")
    print(f"wrote {target}")
    print(f"  {len(items)} items, {n_addressed}/{n_proceed} proceed decisions addressed, "
          + ", ".join(f"{k} {v}" for k, v in sorted(counts.items())))
    if n_addressed < n_proceed:
        print("  fill in the `Or why not` column before handing this over — a blank there is the "
              "omission this table exists to surface")
    return 0


# ── selfcheck ───────────────────────────────────────────────────────────────────────────────

def cmd_selfcheck(a, graph: dict, schema: dict) -> int:
    bad = []
    qs = set(graph["questions"])
    if len(qs) != 41:
        bad.append(f"lens-graph.yaml has {len(qs)} questions, not 41")

    inv = (REFS / "production-inventory.md").read_text()
    inv_ids = set(re.findall(r"\bAGENT(?:OPS|SEC|REL|PERF|COST|SUS)\d{2}\b", inv))
    if qs - inv_ids:
        bad.append(f"in lens-graph.yaml, not in production-inventory.md: {sorted(qs - inv_ids)}")
    if inv_ids - qs:
        bad.append(f"in production-inventory.md, not in lens-graph.yaml: {sorted(inv_ids - qs)}")

    nodes = graph.get("nodes", {})
    survey = (REFS / "survey-and-plan.md").read_text()
    table_nodes = dict(re.findall(r"\|\s*\*\*([A-K]\d?)\*\*[^|]*\|[^|]*\|\s*\[([^\]]+\.md)\]", survey))
    if set(nodes) != set(table_nodes):
        bad.append(f"node ids differ — graph {sorted(set(nodes) - set(table_nodes))}, "
                   f"survey-and-plan.md table {sorted(set(table_nodes) - set(nodes))}")
    for nid, spec in nodes.items():
        f = spec.get("file")
        if not (REFS / f).exists():
            bad.append(f"node {nid} names {f}, which does not exist")
        if nid in table_nodes and table_nodes[nid] != f:
            bad.append(f"node {nid}: graph says {f}, survey-and-plan.md table says {table_nodes[nid]}")

    defined = set(graph["access_classes"])
    used = set()
    for spec in list(graph["questions"].values()) + list(nodes.values()):
        used |= set(spec.get("needs", [])) | set(spec.get("needs_any", []) or [])
    if used - defined:
        bad.append(f"access classes used but not defined: {sorted(used - defined)}")
    if defined - used:
        bad.append(f"access classes defined but unused: {sorted(defined - used)}")
    granted_classes = {c for cs in GRANTS.values() for c in cs} | {"aws"}
    if defined - granted_classes:
        bad.append(f"access classes no survey answer can grant: {sorted(defined - granted_classes)}")

    ev = (REFS / "evidence.md").read_text()
    ev_tags = set(re.findall(r"`\[((?:measured|read|stated):?\w*|verified|docs|reasoned|open)\]`", ev))
    missing = set(schema["evidence_tags"]) - ev_tags
    if missing:
        bad.append(f"tags in record-schema.yaml with no row in evidence.md: {sorted(missing)}")

    for line in bad:
        print(f"ERROR  {line}")
    if not bad:
        print(f"selfcheck: clean — {len(qs)} questions, {len(nodes)} nodes, "
              f"{len(schema['evidence_tags'])} tags, all node files present")
    return 1 if bad else 0


# ── resolve command + entry point ───────────────────────────────────────────────────────────

def cmd_resolve(a, graph: dict, schema: dict) -> int:
    if a.interactive:
        access = {}
        print("Six access questions. Anything you cannot confirm, answer n.\n")
        for key, prompt in SURVEY_PROMPTS:
            access[key] = input(f"{prompt} [y/n] ").strip().lower().startswith("y")
        print()
    else:
        path = pathlib.Path(a.access) if a.access else a.dir / "access.yml"
        if not path.exists():
            return err(f"no {path} — write the survey answers first, or use --interactive")
        access = load_access(path)

    res = resolve(graph, access, {"yes": True, "no": False, "unknown": None}[a.multi_agent])
    if a.format == "yaml":
        print(yaml.dump(res, sort_keys=False, allow_unicode=True))
    else:
        print_resolve(res)
    return 0


def err(msg: str) -> int:
    print(msg, file=sys.stderr)
    return 2


def main() -> int:
    names = ("resolve", "record", "status", "findings", "validate", "selfcheck")
    # Back-compat: `lens_plan.py --access x.yml` still resolves, so an assessment mid-flight does
    # not break on the day this ships.
    argv = sys.argv[1:]
    if argv and argv[0].startswith("-") and argv[0] not in ("-h", "--help") \
            and not any(x in names for x in argv):
        argv = ["resolve"] + argv

    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--dir", type=pathlib.Path, default=DEFAULT_DIR,
                        help="assessment directory (default .agentcore-migration)")
    sub = ap.add_subparsers(dest="cmd", required=True, parser_class=lambda **kw: argparse.ArgumentParser(
        parents=[common], **kw))

    r = sub.add_parser("resolve", help="graph + access → what is reachable")
    r.add_argument("--access")
    r.add_argument("--interactive", action="store_true")
    r.add_argument("--multi-agent", choices=["yes", "no", "unknown"], default="unknown")
    r.add_argument("--format", choices=["text", "yaml"], default="text")
    r.set_defaults(fn=cmd_resolve)

    c = sub.add_parser("record", help="append one validated observation to receipts.jsonl")
    for kind in NODE_KINDS:
        c.add_argument(KIND_FLAGS[kind], dest=kind, metavar="ID")
    c.add_argument("--state")
    c.add_argument("--value")
    c.add_argument("--tag", help="evidence tag; see evidence.md")
    c.add_argument("--evidence", help="what you saw, at file:line where there is one")
    c.add_argument("--source", help="the command you ran or the artifact you opened")
    c.add_argument("--note")
    c.add_argument("--component", help="separates rows that share a practice, or edges of a "
                                       "multi-agent topology")
    c.add_argument("--blocked-by", dest="blocked_by", help="survey or node id, for an unreachable node")
    c.add_argument("--substitute-used", dest="substitute_used")
    c.add_argument("--closed-by", dest="closed_by")
    c.add_argument("--remedy-verified", dest="remedy_verified")
    c.add_argument("--requires-runtime-move", dest="requires_runtime_move")
    c.add_argument("--ineffective-because", dest="ineffective_because")
    c.add_argument("--defect-owner", dest="defect_owner")
    c.add_argument("--blocked-by-artifact", dest="blocked_by_artifact")
    c.add_argument("--compute-type-assumed", dest="compute_type_assumed")
    c.add_argument("--source-of-value", dest="source_of_value")
    c.add_argument("--is-true-high-water-mark", dest="is_true_high_water_mark")
    c.add_argument("--derived-from", dest="derived_from")
    c.add_argument("--how-to-get-it", dest="how_to_get_it")
    c.add_argument("--verified-by", dest="verified_by",
                   help="plan_item: the command actually run. Required for built and failing")
    c.add_argument("--mutation-tested", dest="mutation_tested",
                   help="plan_item: did you break what the test guards and watch it fail?")
    c.add_argument("--artifacts", help="plan_item: comma-separated paths written")
    c.add_argument("--supersedes")
    c.add_argument("--reason", choices=["reinterpretation", "re-observation"])
    c.add_argument("--by", choices=["assessor", "customer", "reviewer"])
    c.add_argument("--batch", metavar="FILE|-", help="JSONL, one receipt per line")
    c.set_defaults(fn=cmd_record)

    s = sub.add_parser("status", help="the frontier: reachable, minus what has a receipt")
    s.add_argument("--access")
    s.add_argument("--multi-agent", choices=["yes", "no", "unknown"], default="unknown")
    s.set_defaults(fn=cmd_status)

    f = sub.add_parser("findings", help="receipts → findings.yml")
    f.set_defaults(fn=cmd_findings)

    v = sub.add_parser("validate", help="referential integrity. Never fails on coverage")
    v.set_defaults(fn=cmd_validate)

    m = sub.add_parser("manifest", help="items.yml + receipts → plan/scaffold/MANIFEST.md")
    m.add_argument("--out", help="plan directory, if /plan wrote it outside .agentcore-migration")
    m.set_defaults(fn=cmd_manifest)

    k = sub.add_parser("selfcheck", help="the instrument: do graph, schema and prose agree?")
    k.set_defaults(fn=cmd_selfcheck)

    a = ap.parse_args(argv)
    return a.fn(a, load_graph(), load_schema())


if __name__ == "__main__":
    sys.exit(main())
