#!/usr/bin/env python3
"""The assessment's set arithmetic and referential integrity. Judgement stays with the model.

Eight subcommands, and the division between them and the assessor is deliberate:

    resolve     graph + access  →  which of the 41 questions and 15 nodes are reachable
    record      append one observation to receipts.jsonl, validated, timestamped
    status      the frontier — what resolve says is reachable, minus what has a receipt
    findings    receipts → findings.yml, applying the supersedes chain
    validate    referential integrity across every artifact. NEVER fails on coverage
    phases      plan graph + record  →  which plan phases are executable   (used by /plan)
    manifest    items.yml + receipts → MANIFEST.md, both indexes           (used by /plan)
    selfcheck   the instrument itself: do the graph, the schema and the prose still agree?

A step belongs here when the reason is that a model under context pressure will skip it — not
when the script seems smarter. `resolve` earns its place because 41 access preconditions do not
fit in working memory. `findings` earns it because supersession chains are fiddly and fail
silently. There is deliberately **no `suggest`**: grouping findings into proposals requires
knowing that one NetworkPolicy closes three questions, which is knowledge of the system and not
set arithmetic. A script attempting it would bundle by pillar or by severity, which is the
"packaging" failure grouping rules exist to prevent. The model authors suggestions.yml;
`validate` checks it.

**This file is the only entry point, and that is deliberate.** Thirteen documents name
`scripts/lens_plan.py`; the implementation is split across lens_core / lens_assess / lens_validate
/ lens_phases for editing, and none of those paths appears in any document or hook. A second
invocable script would mean the model has to know which one to call, and a command that does not
resolve has already cost this project twice.

Artifacts, one writer each, under `.agentcore-migration/`:

    access.yml       survey 1 — what we were permitted to do        written once, by hand
    receipts.jsonl   append-only log of work actually done          appended by `record`
    findings.yml     everything observed, projected from receipts   generated by `findings`
    assessment.yml   the assessor's judgement                       model-authored
    suggestions.yml  grouped proposals, each citing findings        model-authored
    decisions.yml    survey 2 — proceed / decline / defer           written with the human
    plan/            plan.md + items.yml + scaffold/                written by /plan
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

import yaml

from lens_assess import (cmd_findings, cmd_record, cmd_status, print_resolve, resolve)
from lens_core import (DEFAULT_DIR, GRANTS, KIND_FLAGS, NODE_KINDS, REFS, SURVEY_PROMPTS,
                       load_access, load_graph, load_schema, err)
from lens_phases import cmd_manifest, cmd_phases, compute_predicates, load_plan_graph
from lens_validate import cmd_validate


# ── selfcheck ───────────────────────────────────────────────────────────────────────────────

def cmd_selfcheck(a, graph: dict, schema: dict) -> int:
    bad = []
    qs = set(graph["questions"])
    if len(qs) != 41:
        bad.append(f"lens-graph.yaml has {len(qs)} questions, not 41")

    inv = (REFS / "production-inventory.md").read_text()
    inv_ids = set(re.findall(r"\bAGENT(?:OPS|SEC|REL|PERF|COST|SUS)\d{2}\b", inv))
    if qs - inv_ids:
        bad.append(f"in lens-graph.yaml, not in production-inventory.md: {sorted(qs - inv_ids)}")
    if inv_ids - qs:
        bad.append(f"in production-inventory.md, not in lens-graph.yaml: {sorted(inv_ids - qs)}")

    nodes = graph.get("nodes", {})
    survey = (REFS / "survey-and-plan.md").read_text()
    table_nodes = dict(re.findall(r"\|\s*\*\*([A-K]\d?)\*\*[^|]*\|[^|]*\|\s*\[([^\]]+\.md)\]", survey))
    if set(nodes) != set(table_nodes):
        bad.append(f"node ids differ — graph {sorted(set(nodes) - set(table_nodes))}, "
                   f"survey-and-plan.md table {sorted(set(table_nodes) - set(nodes))}")
    for nid, spec in nodes.items():
        f = spec.get("file")
        if not (REFS / f).exists():
            bad.append(f"node {nid} names {f}, which does not exist")
        if nid in table_nodes and table_nodes[nid] != f:
            bad.append(f"node {nid}: graph says {f}, survey-and-plan.md table says {table_nodes[nid]}")

    defined = set(graph["access_classes"])
    used = set()
    for spec in list(graph["questions"].values()) + list(nodes.values()):
        used |= set(spec.get("needs", [])) | set(spec.get("needs_any", []) or [])
    if used - defined:
        bad.append(f"access classes used but not defined: {sorted(used - defined)}")
    if defined - used:
        bad.append(f"access classes defined but unused: {sorted(defined - used)}")
    granted_classes = {c for cs in GRANTS.values() for c in cs} | {"aws"}
    if defined - granted_classes:
        bad.append(f"access classes no survey answer can grant: {sorted(defined - granted_classes)}")

    ev = (REFS / "evidence.md").read_text()
    ev_tags = set(re.findall(r"`\[((?:measured|read|stated):?\w*|verified|docs|reasoned|open)\]`", ev))
    missing = set(schema["evidence_tags"]) - ev_tags
    if missing:
        bad.append(f"tags in record-schema.yaml with no row in evidence.md: {sorted(missing)}")

    # The plan graph. A predicate named in a phase's `needs` with no implementation would resolve as
    # unknown and quietly degrade the phase — a checker that reports "we could not tell" about
    # something nobody ever tried to tell. That is worse than a crash, so it is checked here.
    pg = load_plan_graph()
    declared = set(pg["predicates"])
    implemented = set(compute_predicates(pathlib.Path("/nonexistent"), {}))
    if declared - implemented:
        bad.append(f"predicates declared in plan-graph.yaml with no implementation in "
                   f"compute_predicates: {sorted(declared - implemented)}")
    if implemented - declared:
        bad.append(f"predicates implemented but undocumented in plan-graph.yaml: "
                   f"{sorted(implemented - declared)}")
    used_p: set[str] = set()
    for spec in pg["phases"].values():
        used_p |= set(spec.get("needs") or []) | set(spec.get("degraded_if") or [])
    if used_p - declared:
        bad.append(f"phases reference undeclared predicates: {sorted(used_p - declared)}")
    if declared - used_p:
        bad.append(f"predicates declared but used by no phase: {sorted(declared - used_p)}")
    outcomes = set(schema["outcomes"])
    for pid, spec in pg["phases"].items():
        for o in (spec.get("only_if") or {}).get("outcome") or []:
            if o not in outcomes:
                bad.append(f"phase {pid}: only_if outcome `{o}` is not in record-schema.yaml")
        for dep in spec.get("after") or []:
            if dep not in pg["phases"]:
                bad.append(f"phase {pid}: after `{dep}`, which is not a phase")

    for line in bad:
        print(f"ERROR  {line}")
    if not bad:
        print(f"selfcheck: clean — {len(qs)} questions, {len(nodes)} nodes, "
              f"{len(schema['evidence_tags'])} tags, all node files present")
    return 1 if bad else 0


# ── resolve command + entry point ───────────────────────────────────────────────────────────

def cmd_resolve(a, graph: dict, schema: dict) -> int:
    if a.interactive:
        access = {}
        print("Six access questions. Anything you cannot confirm, answer n.\n")
        for key, prompt in SURVEY_PROMPTS:
            access[key] = input(f"{prompt} [y/n] ").strip().lower().startswith("y")
        print()
    else:
        path = pathlib.Path(a.access) if a.access else a.dir / "access.yml"
        if not path.exists():
            return err(f"no {path} — write the survey answers first, or use --interactive")
        access = load_access(path)

    res = resolve(graph, access, {"yes": True, "no": False, "unknown": None}[a.multi_agent])
    if a.format == "yaml":
        print(yaml.dump(res, sort_keys=False, allow_unicode=True))
    else:
        print_resolve(res)
    return 0


def main() -> int:
    names = ("resolve", "record", "status", "findings", "validate", "selfcheck")
    # Back-compat: `lens_plan.py --access x.yml` still resolves, so an assessment mid-flight does
    # not break on the day this ships.
    argv = sys.argv[1:]
    if argv and argv[0].startswith("-") and argv[0] not in ("-h", "--help") \
            and not any(x in names for x in argv):
        argv = ["resolve"] + argv

    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--dir", type=pathlib.Path, default=DEFAULT_DIR,
                        help="assessment directory (default .agentcore-migration)")
    sub = ap.add_subparsers(dest="cmd", required=True, parser_class=lambda **kw: argparse.ArgumentParser(
        parents=[common], **kw))

    r = sub.add_parser("resolve", help="graph + access → what is reachable")
    r.add_argument("--access")
    r.add_argument("--interactive", action="store_true")
    r.add_argument("--multi-agent", choices=["yes", "no", "unknown"], default="unknown")
    r.add_argument("--format", choices=["text", "yaml"], default="text")
    r.set_defaults(fn=cmd_resolve)

    c = sub.add_parser("record", help="append one validated observation to receipts.jsonl")
    for kind in NODE_KINDS:
        c.add_argument(KIND_FLAGS[kind], dest=kind, metavar="ID")
    c.add_argument("--state")
    c.add_argument("--value")
    c.add_argument("--tag", help="evidence tag; see evidence.md")
    c.add_argument("--evidence", help="what you saw, at file:line where there is one")
    c.add_argument("--source", help="the command you ran or the artifact you opened")
    c.add_argument("--note")
    c.add_argument("--component", help="separates rows that share a practice, or edges of a "
                                       "multi-agent topology")
    c.add_argument("--blocked-by", dest="blocked_by", help="survey or node id, for an unreachable node")
    c.add_argument("--substitute-used", dest="substitute_used")
    c.add_argument("--closed-by", dest="closed_by")
    c.add_argument("--remedy-verified", dest="remedy_verified")
    c.add_argument("--requires-runtime-move", dest="requires_runtime_move")
    c.add_argument("--ineffective-because", dest="ineffective_because")
    c.add_argument("--defect-owner", dest="defect_owner")
    c.add_argument("--blocked-by-artifact", dest="blocked_by_artifact")
    c.add_argument("--compute-type-assumed", dest="compute_type_assumed")
    c.add_argument("--source-of-value", dest="source_of_value")
    c.add_argument("--is-true-high-water-mark", dest="is_true_high_water_mark")
    c.add_argument("--derived-from", dest="derived_from")
    c.add_argument("--how-to-get-it", dest="how_to_get_it")
    c.add_argument("--verified-by", dest="verified_by",
                   help="plan_item: the command actually run. Required for built and failing")
    c.add_argument("--mutation-tested", dest="mutation_tested",
                   help="plan_item: did you break what the test guards and watch it fail?")
    c.add_argument("--artifacts", help="plan_item: comma-separated paths written")
    c.add_argument("--supersedes")
    c.add_argument("--reason", choices=["reinterpretation", "re-observation"])
    c.add_argument("--by", choices=["assessor", "customer", "reviewer"])
    c.add_argument("--batch", metavar="FILE|-", help="JSONL, one receipt per line")
    c.set_defaults(fn=cmd_record)

    s = sub.add_parser("status", help="the frontier: reachable, minus what has a receipt")
    s.add_argument("--access")
    s.add_argument("--multi-agent", choices=["yes", "no", "unknown"], default="unknown")
    s.set_defaults(fn=cmd_status)

    f = sub.add_parser("findings", help="receipts → findings.yml")
    f.set_defaults(fn=cmd_findings)

    v = sub.add_parser("validate", help="referential integrity. Never fails on coverage")
    v.set_defaults(fn=cmd_validate)

    p = sub.add_parser("phases", help="plan graph + record → which phases are executable")
    p.add_argument("--access")
    p.add_argument("--outcome", help="override decisions.yml's outcome, to see another track")
    p.add_argument("--format", choices=["text", "yaml"], default="text")
    p.set_defaults(fn=cmd_phases)

    m = sub.add_parser("manifest", help="items.yml + receipts → plan/scaffold/MANIFEST.md")
    m.add_argument("--out", help="plan directory, if /plan wrote it outside .agentcore-migration")
    m.set_defaults(fn=cmd_manifest)

    k = sub.add_parser("selfcheck", help="the instrument: do graph, schema and prose agree?")
    k.set_defaults(fn=cmd_selfcheck)

    a = ap.parse_args(argv)
    return a.fn(a, load_graph(), load_schema())


if __name__ == "__main__":
    sys.exit(main())
